const animalSummoning = {
    "Name": "Animal Summoning",
    "Manifest": "Manifestation Roll 1d4: (1) an egg shimmers into existence, then hatches into the animal summoned; (2) a flash of dark clouds and the animal appears; (3) the animal’s skeleton appears first, then organs appear, then muscles knit them together, then skin grows, and the animal appears; (4) animal erupts from the ground fully formed",
    "range1": "Lost, failure, and worse! Roll 1d6 modified by Luck: (0 or less) corruption + misfire + patron taint, 1-2 corruption gained, 3 patron taint (or corruption if no patron),4+) misfire.",
    "range2to11": "lost, spell failure.",
    "range12to13": "The caster summons one mundane animal of 1 HD or less. The animal remains for up to 1 hour, though it hungers, thirsts, and rests as normal. The animal obeys the caster’s commands within normal bounds – suicidal commands or those contrary to its nature (e.g., ordering a rabbit to consume meat) have a 50% chance of releasing the animal from service, in which case it returns from whence it came. Due to the nature of the summoning, the caster cannot directly harm the creature summoned.",
    "range14to17": "The caster summons one mundane animal of up to 2 HD, or two animals of 1 HD or less. The animals remain for up to 1 hour, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to its nature (e.g., ordering a rabbit to consume meat) have a 50% chance of releasing the animal from service, in which case it returns from whence it came. Due to the nature of the summoning, the caster cannot directly harm the creature summoned.",
    "range18to19": "The caster summons one mundane animal of up to 2 HD, or two animals of 1 HD or less. The animals remain for up to 2 hours, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to its nature (e.g., ordering a rabbit to consume meat) have a 50% chance of releasing the animal from service, in which case it returns from whence it came. Due to the nature of the summoning, the caster cannot directly harm the creature summoned.",
    "range20to23": "The caster summons one mundane animal of up to 4 HD, two animals of 2 HD, or up to four animals of 1 HD or less. The animals remain for up to 2 hours, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to its nature (e.g., ordering a rabbit to consume meat) have a 25% chance of releasing the animal from service, in which case it returns from whence it came. Due to the nature of the summoning, the caster cannot di- rectly harm the creature summoned.",
    "range24to27": "The caster summons one mundane animal of up to 8 HD, two animals of 4 HD, four animals of 2 HD, or up to eight animals of 1 HD or less. The animals remain for up to 2 hours, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to their nature (e.g., ordering a rabbit to consume meat) have a 25% chance of releasing the animals from service, in which case they return to whence they came. Due to the nature of the summon-ing, the caster cannot directly harm the animals summoned",
    "range28to29": "The caster summons one mundane animal of up to 8 HD, two animals of 4 HD, four animals of 2 HD, or up to eight animals of 1 HD or less. The animals remain for up to a day, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to their nature (e.g., ordering a rabbit to consume meat) have a 10% chance of releasing the animals from service, in which case they return to whence they came. Due to the nature of the summon-ing, the caster cannot directly harm the animals summoned.",
    "range30to31": "The caster summons one mundane animal of up to 16 HD, two animals of up to 8 HD, four animals of up to 4 HD, or up to eight animals of 2 HD or less. The animals remain for up to a day, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands within normal bounds – suicidal commands or those contrary to their nature (e.g., ordering a rabbit to consume meat) have a 10% chance of releasing the animals from service, in which case they return to whence they came. Due to the nature of the summoning, the caster cannot directly harm the animals summoned.",
    "range32plus": "The caster summons a large group of mundane animals. This could be a herd of cattle, a pride of lions, a flock of geese, or a pack of wolves. All animals must be of the same type, and the total hit dice must be 100 HD or less. The herd remains for up to a week, though they hunger, thirst, and rest as normal. The animals obey the caster’s commands and even undertake suicidal commands or those contrary to their nature (e.g., ordering a rabbit to consume meat). Due to the nature of the summoning, the caster cannot directly harm the animals summoned."

}
console.log(animalSummoning.range30to31);
